Skip seen maps when fetching next RMT map
GreepTheSheep/openplanet-MXRandom pull request #116
Opened 2023-10-30 06:27 UTC by tgrieger

There are times where maps are reused, expecially when providing a custom mappack. This caches the TrackUID in a dictionary and skips any already seen maps.

Tested with a mappack that has a single map in it: https://trackmania.exchange/mappack/view/3745

2023-10-31 14:30 UTC, GreepTheSheep commented on src/Utils/RMC/RMT.as
> +            if (string(seenMaps[nextMap.TrackUID]).Length > 0) {
Can you please change to [`Exists()`](https://openplanet.dev/docs/api/global/dictionary/Exists) function ?

2023-10-31 14:30 UTC, GreepTheSheep requested changes
See comment

2023-10-31 17:22 UTC, tgrieger commented on src/Utils/RMC/RMT.as
> +            if (string(seenMaps[nextMap.TrackUID]).Length > 0) {
Yeah! I was looking at the angelscript docs for dictionaries and it said the method was `exists` but I was getting an error. Verified `Exists` works though. Thanks!

2023-11-08 02:42 UTC, tgrieger commented
@GreepTheSheep I've updated per your comments. Please let me know if there's anything else.

2023-11-12 15:12 UTC, GreepTheSheep approved these changes

2023-11-12 15:12 UTC, merged