fix: fix issue caused by incorrect handle assignment
GreepTheSheep/openplanet-MXRandom pull request #82
Opened 2023-06-03 18:30 UTC by EdVraz

fixes an issue introduces in the last PR because of my misunderstanding of how handles work.

Apologies for not testing properly, I just assumed the change is simple enough to not require a test

2023-06-05 14:22 UTC, GreepTheSheep requested changes
I think I added some `preloadedMap = null` on other RMC.as files. Can you do a global search and replace to your method ? Thanks

2023-06-05 14:24 UTC, EdVraz commented
> I think I added some `preloadedMap = null` on other RMC.as files. Can you do a global search and replace to your method ? Thanks

The script compilation would fail if you did that (that's how I noticed in the end) but I'll check in a second

2023-06-05 14:46 UTC, EdVraz commented
Yeah I can't see anything that is not assigned to `null` without an `@`, all fine 👍

2023-06-05 14:51 UTC, GreepTheSheep requested changes

2023-06-05 14:51 UTC, GreepTheSheep commented on src/Utils/RMC/GlobalProperties.as
> +            MX::clearPreloadedMap();
So I think better way is `@MX::preloadedMap = null;` with an `@` at this point ?

2023-06-07 09:49 UTC, GreepTheSheep approved these changes

2023-06-07 09:49 UTC, merged